spring:
  ai:
    llama-cpp:
      model-path: models/ELYZA-japanese-Llama-2-7b-fast-instruct-q2_K.gguf
  application:
    name: api-sample-graalvm
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      probes:
        enabled: true